### ISSUE TITLE
Will - Remove "Bruce Danger" from footer

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-DangerLaw#13]
![Screen Shot 2023-10-13 at 2 11 03 PM](https://github.com/LemmaLegalConsulting/docassemble-DangerLaw/assets/65858862/61ab8f1d-f559-40f8-a039-dc457c6e3c9b)

**Comment by tobyfey** [comment]
Should the footers be standardized? #18

**Comment by miabonardi** [comment]
Can you ask Annika this question on Trello or via email?
