### ISSUE TITLE
Will - Is there supposed to be an extra blank page at end of will?

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-DangerLaw#18]
![Screen Shot 2023-10-13 at 2 17 36 PM](https://github.com/LemmaLegalConsulting/docassemble-DangerLaw/assets/65858862/dd5e6436-614a-4fba-8581-67861b25cb77)

**Comment by tobyfey** [comment]
This could be easily fixed if we standardized the footers.

**Comment by tobyfey** [comment]
Now that creates a blank page on the first page of the testamentary trust. I moved title page and table of contents.  Now table of contents isn't showing up
