### ISSUE TITLE
Use clients[0].phone_numbers() to format phone number in DOCX

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-DangerLaw#3]

**Comment by miabonardi** [comment]
@nonprofittechy How do I format it when it is in the doc like this? 

![Screen Shot 2023-10-11 at 10 36 13 AM](https://github.com/LemmaLegalConsulting/docassemble-DangerLaw/assets/65858862/d8742b17-86dd-46ab-a63b-f3872fc27b47)

**Comment by nonprofittechy** [comment]
Use clients[0].phone_numbers() to automatically format the number and print all numbers in a list. Or use phone_number_formatted(clients[0].phone_number)
